version: '3.8'

services:
  mysql:
    image: mysql:9.2.0
    restart: always
    env_file:
      - variables.env
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
  
